services:
  - type: web
    name: ads-capture
    runtime: docker
    plan: free
    region: singapore
    rootDir: ad-capture
    envVars:
      - key: PORT
        value: 3000
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: BROWSER_STORAGE_STATE_B64
        sync: false
      - key: PROXY_SERVER
        sync: false
      - key: PROXY_USERNAME
        sync: false
      - key: PROXY_PASSWORD
        sync: false
